'use strict';

// The words of Solarljos's page, by key. app.js looks every string up with tr(key, params);
// nothing the page says is written anywhere else. The table below is English, the source of
// every other language, and the one shown for any key another language leaves out.
//
//   - Placeholders are named, {name} or {count}, never {0}: a language that puts the verb last
//     must be free to move them. A number put in is written as the language writes numbers.
//   - A value may be a set of plural forms, { one, other } here, chosen by the language's plural
//     rules (Intl.PluralRules) on params.count.
//   - meta.* is not shown. meta.locale decides how dates and numbers are written (en-GB writes
//     "27 Sep 2026, 21:14"), meta.lang and meta.dir go on <html>.
//   - kind.<kind> and kindHelp.<kind> are keyed by the library's own name for a kind of copy
//     (src/quality.js), so they follow it; a kind with no entry is shown by that name.
//   - source.<id>.* is keyed by the source's id; a source with no entry shows the library's label.
//
// Every other language is a file of its own beside this one, lang/<code>.json, where <code> is
// one of the codes of src/i18n.js's LOCALES: ko ja zh-CN zh-TW es fr de pt-BR ru it pl tr vi id
// th ar hi. The page offers the languages whose file is there, by the name LOCALES gives each,
// and asks for a file only when its language is chosen. A file is JSON in UTF-8, one flat object
// from a key of the table below to its words:
//
//   {
//     "meta.lang": "ru",
//     "meta.locale": "ru-RU",
//     "meta.dir": "ltr",
//     "nav.find": "Найти файл",
//     "results.title.name": "Результаты для «{name}»",
//     "results.files": { "one": "{count} файл", "few": "{count} файла", "many": "{count} файлов", "other": "{count} файла" }
//   }
//
//   - meta.lang is the language's tag as it goes on <html lang>: the file's code ("ko", "zh-CN",
//     "pt-BR"), which also picks the language's fonts (style.css). meta.locale is the locale
//     Intl writes dates and numbers in, and whose plural rules count: "ko-KR", "de-DE", "pt-BR";
//     "ar-EG" writes Arabic-Indic digits, "ar-u-nu-latn" Latin ones. meta.dir is "rtl" for Arabic
//     and "ltr" for every other language here. Each must be of the file's language; one left
//     out is taken from the code.
//   - A key is one of the table below. A key it does not have is left out, and so is any value
//     that breaks a rule here: English shows in its place.
//   - A value is a string, or, for a key whose English value is a set of plural forms or has
//     {count}, an object of plural forms: keyed by the Intl.PluralRules categories of the language
//     -- zero, one, two, few, many, other -- with "other" always there. A form the language has
//     and the file lacks falls back to "other"; a plain string serves every count, which suits a
//     language with one form only (Korean, Japanese, Chinese, Thai, Vietnamese, Indonesian).
//   - Every form uses every placeholder the English value uses, in any of its forms, and no other,
//     by the same names: {name} stays {name}. Only {count} may be left out, and only by a form
//     that stands for one number alone -- English "one" is 1 and may say "1 file"; Russian "one"
//     is also 21 and 31, French "one" also 0, and must say {count}.
//   - Text is plain: no markup, which would be shown as it is. Typographic quotes and the
//     language's own punctuation are welcome.
//
// test/gui-lang.test.js checks every file there against these rules, so a key misspelt, a
// placeholder dropped or renamed, or a plural form that cannot be right fails the tests.
//
// What the library itself says -- a source's notes, a refusal's reason -- comes from src/i18n.js
// t(), in the language the server speaks; the page tells the server the language it is shown in.

(function (root) {
  const en = {
    'meta.lang': 'en',
    'meta.locale': 'en-GB',
    'meta.dir': 'ltr',

    // ---- the frame of the page ----
    'app.name': 'Solarljos',
    'app.pageTitle': '{page} · Solarljos',
    'app.skip': 'Skip to main content',
    'nav.label': 'Main',
    'nav.find': 'Find a file',
    'nav.media': 'Photos and videos',
    'nav.folder': 'Bring back a folder',
    'nav.sources': 'What is searched',
    'nav.help': 'Help',
    'nav.quit': 'Quit',
    'nav.toggle': 'Menu',
    'lang.label': 'Language',
    'lang.changed': 'The page is now in {language}.',
    'lang.failed': 'That language could not be loaded. The page stays in {language}.',
    'theme.toLight': 'Switch to the light theme',
    'theme.toDark': 'Switch to the dark theme',
    'quit.confirmTitle': 'Quit Solarljos?',
    'quit.confirmBody': 'The results on this page will be gone. Files you restored stay where you put them.',
    'quit.done.title': 'Solarljos has stopped',
    'quit.done.body': 'You can close this window.',
    'quit.done.writing': 'Solarljos stops as soon as the files being written are done. You can close this window then.',

    // ---- the Windows program's own (desktop/Solarljos), which shows the rest of this table too ----

    'desktop.starting': 'Getting ready to search…',
    'desktop.missing.title': 'Part of Solarljos is missing',
    'desktop.missing.body': 'solarljos-core.exe, the part of Solarljos that searches, has to be in the same folder as Solarljos.exe. Keep the files of the download together, and start Solarljos.exe again.',
    'desktop.stopped.title': 'Solarljos stopped searching',
    'desktop.stopped.body': 'The part of Solarljos that searches has stopped. Files you restored stay where you put them. Start Solarljos again to go on.',
    'desktop.stopped.said': 'What it said last',
    'conn.lost.title': 'Solarljos has stopped',
    'conn.lost.body': 'Nothing more can be searched or restored from this page. Start Solarljos again, then try again here.',
    'conn.forbidden.title': 'This page is not connected to Solarljos',
    'conn.checking': 'Checking…',
    'conn.lost.still': 'Solarljos still does not answer.',

    'common.advanced': 'More options',
    'common.back': 'Back',
    'common.cancel': 'Cancel',
    'common.clearSelection': 'Clear selection',
    'common.close': 'Close',
    'common.collapseAll': 'Collapse all',
    'common.copied': 'Copied',
    'common.copyFailed': 'The path could not be copied. Select it and copy it by hand.',
    'common.copyPath': 'Copy the path',
    'common.details': 'Details',
    'common.done': 'Done',
    'common.expandAll': 'Expand all',
    'common.newSearch': 'New search',
    'common.optional': '(optional)',
    'common.pathTip': 'In File Explorer, hold Shift, right-click the folder and choose “Copy as path”, then paste it here.',
    'common.retry': 'Try again',
    'common.searchAgain': 'Search again',
    'common.stop': 'Stop',
    'common.stopping': 'Stopping…',
    'common.unknown': 'unknown',

    'fmt.bytes': '{n} B',
    'fmt.kb': '{n} KB',
    'fmt.mb': '{n} MB',
    'fmt.gb': '{n} GB',
    'fmt.tb': '{n} TB',
    'fmt.dimensions': '{w} × {h}',
    'fmt.dateUnknown': 'date unknown',
    'fmt.sizeUnknown': 'size unknown',
    'fmt.elapsed': '{s} s',

    'a11y.sourceDone': '{source}: {result}',
    'a11y.progressValue': '{source}: {done} of {total}',
    'a11y.searchDone': { one: 'Search done: 1 copy found.', other: 'Search done: {count} copies found.' },
    'a11y.planDone': { one: 'Done: 1 file found.', other: 'Done: {count} files found.' },

    // ---- start ----
    'home.file.title': 'A file',
    'home.file.body': 'A document, a spreadsheet, a piece of code. Search by its name.',
    'home.media.title': 'Photos or videos',
    'home.media.body': 'Pictures and videos, even ones whose name you don’t know. Search by type and date.',
    'home.folder.title': 'A whole folder',
    'home.folder.body': 'Everything that was inside a folder, brought back as it was laid out.',
    'home.lastIn': '{place}: back to your last results ({count})',
    'home.good.title': 'Good to know',
    'home.good.copies': 'Solarljos looks for copies that Windows and your apps kept: the Recycle Bin, restore points, editor history and more. It changes nothing on this PC unless you ask it to put something back, and then only in the folder you choose.',
    'home.good.soon': 'Search soon. Many of these copies are cleared after days or weeks.',
    'home.good.drive': 'Lost something from a USB stick, a memory card or a hard disk? Save nothing new onto it until you are done.',
    'home.good.exe': 'Don’t copy Solarljos.exe, or anything else, onto the card or drive you are recovering from.',
    'home.good.cleanup': 'Until you are done, don’t run Disk Cleanup and don’t clear your browser’s history or cache: they erase smaller copies of pictures that Windows and the browser keep.',
    'home.good.window': 'Solarljos runs while this window is open. Closing the window, or Quit, stops it.',
    'home.sourcesLink': 'See what can be searched on this PC',

    // ---- the forms ----
    'form.toResults': 'Back to the results',
    'form.toSearch': 'Back to the search under way',
    'find.title': 'Find a file',
    'find.name.label': 'File name, or part of it',
    'find.name.hint': 'For example budget, report.docx or *.hwp. Upper and lower case don’t matter.',
    'find.name.missing': 'Type a name, a word the file contained, or choose a kind of file under More options.',
    'find.where.label': 'Where was it?',
    'find.where.hint': 'The folder it was in, if you remember. It can be a folder that no longer exists.',
    'find.containing.label': 'A word or phrase it contained',
    'find.containing.hint': 'Slower: every copy found is read. Does not look inside Word, Excel or Hangul (HWP) files.',
    'find.deletedOnly.label': 'Only files that are gone now',
    'find.deletedOnly.hint': 'Leave this off to also see older versions of files that still exist. It can be changed on the results too.',
    'find.since.label': 'Only copies from',
    'find.since.any': 'Any time',
    'find.since.day': 'The last 24 hours',
    'find.since.week': 'The last 7 days',
    'find.since.month': 'The last 30 days',
    'find.since.pick': 'A day I choose',
    'find.since.date': 'From',
    'find.since.missing': 'Choose a day that exists.',
    'find.since.hint': 'Copies that carry no date are kept, since how old they are cannot be told.',
    'find.type.label': 'Kind of file',
    'find.type.any': 'Any kind',
    'find.submit': 'Search',

    'type.document': 'Documents',
    'type.image': 'Pictures',
    'type.video': 'Videos',
    'type.audio': 'Sound and music',
    'type.archive': 'Archives, such as ZIP',
    'type.text': 'Text and code',

    'adv.sources.label': 'Places to search',
    'adv.sources.all': 'All places',
    'adv.sources.textOnly': 'keeps only text',
    'adv.sources.needsAdmin': 'needs administrator rights',
    'adv.sources.none': 'Choose at least one place.',
    'adv.otherDisk.label': 'Another disk',
    'adv.otherDisk.hint': 'To search a drive taken out of another computer, or a memory card’s image, add its folders first.',
    'adv.otherDisk.count': { one: '1 place from another disk is added.', other: '{count} places from another disk are added.' },
    'adv.otherDisk.link': 'Add them under What is searched',
    'adv.onlyAdded.label': 'Search only the places I added',

    // ---- photos and videos ----
    'media.title': 'Find photos and videos',
    'media.expect': 'Photos deleted long ago from this PC’s SSD usually survive only as smaller copies, in restore points, in chat apps or in cloud backups. The original may be gone for good.',
    'media.video': 'Old videos rarely survive on an SSD. Once deleted, the drive erases them, and Windows keeps at most a still picture of a video, never the video. A whole video is most likely in the Recycle Bin, in a restore point, on the card or phone it came from, or in a cloud backup.',
    'media.card.title': 'Photos from a memory card or USB stick',
    'media.card.body': 'Cards and sticks usually keep deleted files longer than an SSD, since their data is not erased at once. Reading one directly needs administrator rights: quit Solarljos, right-click Solarljos.exe and choose “Run as administrator”. Or make an image of the card with another tool and add it under “What is searched”. Set the card’s lock switch before you put it in, and copy nothing onto it, Solarljos.exe included.',
    'media.card.admin': 'Solarljos is running as administrator, so it can read a memory card or USB stick directly: add its drive letter, such as E:, under “What is searched”. Set the card’s lock switch first, and save nothing onto it.',
    'media.frozen': 'Explorer’s thumbnails were read when Solarljos started, before this window opened, so what Windows adds to them from now on cannot push out what was there.',
    'media.what.label': 'What are you looking for?',
    'media.what.photos': 'Photos',
    'media.what.videos': 'Videos',
    'media.what.missing': 'Choose photos, videos or both.',
    'media.when.label': 'From when?',
    'media.when.any': 'Any time',
    'media.when.thisYear': 'This year',
    'media.when.lastYear': 'Last year',
    'media.when.pick': 'Dates I choose',
    'media.when.from': 'From',
    'media.when.to': 'To',
    'media.when.bad': 'That date does not exist.',
    'media.when.badRange': 'The “from” date is after the “to” date.',
    'media.when.missing': 'Choose a date to start from, one to end at, or both.',
    'media.when.hint': 'This is the date each copy carries: when it was deleted, last changed or stored. A photo taken long ago can show a later date. Copies that carry no date are always shown, in a group of their own.',
    'media.where.label': 'Where were they?',
    'media.where.hint': 'For example your Pictures folder, or the folder a camera or phone copied them into. It can be one that no longer exists.',
    'media.smaller.label': 'Include smaller copies',
    'media.smaller.hint': 'When a photo itself is gone, Windows or an app may still have a smaller picture of it. It is always marked as a smaller copy.',
    'media.web.label': 'Include pictures from web pages I visited',
    'media.web.hint': 'Off by default: there are usually thousands, and they are not your own photos.',
    'media.submit': 'Search',

    // ---- bring back a folder ----
    'folder.title': 'Bring back a folder',
    'folder.path.label': 'Which folder was it?',
    'folder.path.hint': 'Type the folder as it was, even though it no longer exists, such as C:\\Users\\you\\Documents\\thesis.',
    'folder.path.missing': 'Type the folder, starting with the drive letter.',
    'folder.path.relative': 'Start with the drive letter, such as C:\\.',
    'folder.deletedOnly.label': 'Only files that are missing now',
    'folder.deletedOnly.hint': 'Use this to fill in a folder that was only partly deleted.',
    'folder.since.label': 'Only versions from',
    'folder.since.hint': 'Only copies from that day on are used; for a file whose copies are all older, none is.',
    'folder.submit': 'Find everything that was inside',

    'plan.title': { one: 'Found 1 file that was inside {folder}', other: 'Found {count} files that were inside {folder}' },
    'plan.explain': 'For each file, the newest exact copy is used. If there is none, an inexact one; then text that was never saved. Smaller copies, and copies that may be incomplete, are used only if you tick them below.',
    'plan.n.exact': '{count} exact',
    'plan.n.inexact': '{count} inexact',
    'plan.n.draft': '{count} never saved',
    'plan.from': 'Taken from: {list}',
    'plan.fromKind': '{kind}: {count}',
    'plan.oldFiles': 'This includes every file ever found below this folder, also ones removed long ago on purpose. Untick what you don’t want back.',
    'plan.filter.label': 'Show',
    'plan.filter.all': 'All files',
    'plan.filter.draft': 'Never saved only',
    'plan.filter.inexact': 'Inexact only',
    'plan.filter.exists': 'Still on disk only',
    'plan.keys': 'In the list, arrow keys move, Right and Left open and close a folder, Space ticks or unticks, and Enter shows a file.',
    'plan.treeLabel': 'Files that were inside {folder}',
    'plan.folderCount': { one: '1 file', other: '{count} files' },
    'plan.stillThere': 'Still on disk',
    'plan.conflict': 'A file in one copy and a folder in another: both come back, the file with “(recovered 2)” in its name.',
    'plan.leftOut.title': { one: 'Only a smaller copy, or one that may be incomplete, is left of 1 file', other: 'Only smaller copies, or ones that may be incomplete, are left of {count} files' },
    'plan.leftOut.body': 'These are not ticked: a smaller copy is not the file, and one that may be incomplete can hold pieces of another. A ticked one is saved with “(smaller copy)” or “(may be incomplete)” in its name.',
    'plan.selected': { one: 'Will write {count} file ({size}) into a new folder.', other: 'Will write {count} files ({size}) into a new folder.' },
    'plan.none': 'Nothing is ticked.',
    'plan.write': { one: 'Bring back {count} file…', other: 'Bring back {count} files…' },

    'rebuild.dialogTitle': 'Bring back {folder}',
    'rebuild.submit': { one: 'Bring back {count} file', other: 'Bring back {count} files' },
    'rebuild.writing': 'Bringing the folder back…',
    'rebuild.progress': 'Writing {done} of {total}…',
    'rebuild.progressUnknown': 'Writing…',
    'rebuild.done': { one: 'Brought back {written} of {count} file', other: 'Brought back {written} of {count} files' },
    'rebuild.into': 'Written into',
    'rebuild.byKind': 'Where the files came from',
    'rebuild.failed': { one: '1 file could not be read or written:', other: '{count} files could not be read or written:' },
    'rebuild.failedBecause': 'The folder could not be written: {message}',
    'rebuild.back': 'Back to the list',

    // ---- searching ----
    'progress.title.name': 'Looking for “{name}”…',
    'progress.title.containing': 'Looking for files containing “{text}”…',
    'progress.title.type': 'Looking for files of the kind: {type}…',
    'progress.title.media': 'Looking for photos and videos…',
    'progress.title.folder': 'Collecting everything that was inside {folder}…',
    'progress.overall': 'Places done: {done} of {total}',
    'progress.waiting': 'Waiting',
    'progress.running': 'Searching…',
    'progress.files': '{done} of {total}',
    'progress.found': { one: '1 found', other: '{count} found' },
    'progress.nothing': 'Nothing',
    'progress.failed': 'Could not be searched',
    'progress.skipped': 'Left out: it keeps only text',
    'progress.vssLast': 'Checked last, in the folders where something turned up',
    'progress.filtering': 'Checking contents and merging copies of the same file…',
    'progress.slow': 'The slowest places are usually Claude Code records and restore points.',
    'progress.failedBecause': 'The search could not finish: {message}',
    'progress.stopped.title': 'Search stopped',
    'progress.stopped.body': 'Nothing was kept from it.',
    'progress.busy.title': 'Another search is still running',
    'progress.busy.body': 'Stop it and start this one?',
    'progress.busy.ok': 'Stop it and search',

    // ---- results ----
    'results.title.name': 'Results for “{name}”',
    'results.title.containing': 'Files containing “{text}”',
    'results.title.type': 'Files of the kind: {type}',
    'results.summary': '{files}, {copies}',
    'results.files': { one: '1 file', other: '{count} files' },
    'results.copies': { one: '1 copy', other: '{count} copies' },
    'results.loading': 'Getting the results again: {count} of {total}…',
    'results.failedPlaces': { one: '1 place could not be searched.', other: '{count} places could not be searched.' },
    'results.notes': 'What the places searched had to say',
    'results.oldLanguage': 'These were found before the language was changed: what the places searched had to say is in the language Solarljos spoke then.',
    'results.view.label': 'Show',
    'results.view.files': 'By file',
    'results.view.list': 'All copies',
    'results.sort.label': 'Sort',
    'results.sort.newest': 'Newest first',
    'results.sort.oldest': 'Oldest first',
    'results.sort.name': 'Name',
    'results.sort.size': 'Size',
    'results.filter.label': 'Filter these results',
    'results.deletedOnly': 'Only files that are gone now',
    'results.showNotDeleted': 'Show files that still exist too',
    'results.allDates': 'Also show copies outside the dates chosen',
    'results.allPlaces': 'Also show copies from outside {folder}',
    'results.hiddenCount': '({count} hidden)',
    'results.allHidden': { one: 'The one copy found is hidden by the choices above.', other: 'All {count} copies found are hidden by the choices above.' },
    'results.undatedKept': { one: '1 copy carries no date. It is shown, since how old it is cannot be told.', other: '{count} copies carry no date. They are shown, since how old they are cannot be told.' },
    'results.noMatch': 'Nothing matches.',
    'results.best': 'Best copy:',
    'results.newerDraft': 'A newer version exists that was never saved ({when}). Look at it too.',
    'results.newerOther': 'A newer copy exists ({when}), but it is less certain: {tier}.',
    'results.versions': { one: '1 other copy', other: '{count} other copies' },
    'results.foundIn': 'Found in',
    'results.foundInMany': { one: '{kind} and 1 more place', other: '{kind} and {count} more places' },
    'results.when': 'Date',
    'results.size': 'Size',
    'results.quality': 'Copy',
    'results.state': 'Now',
    'results.path': 'Was at',
    'results.id': 'ID',
    'results.actions': 'Actions',
    'results.folderUnknown': 'Folder unknown',
    'results.nameUnknown': 'Name unknown',
    'results.nameUnknownLong': 'Name and folder unknown; a {ext} file',
    'results.nameOnly': '{name} (folder unknown)',
    'results.preview': 'Preview',
    'results.about': 'Details',
    'results.restore': 'Restore…',
    'results.rebuildFolder': 'Bring back this folder from every place…',
    'results.showMore': { one: 'Show 1 more', other: 'Show {count} more' },

    // ---- photo grid ----
    'grid.title': 'Photos and videos found',
    'grid.count.photos': { one: '1 photo', other: '{count} photos' },
    'grid.count.videos': { one: '1 video', other: '{count} videos' },
    'grid.count.smaller': { one: '1 of them a smaller copy', other: '{count} of them smaller copies' },
    'grid.noVideos': 'No videos were found. Old videos rarely survive on an SSD: look on the card or phone they came from, or in a cloud backup.',
    'grid.undatedNote': { one: '1 copy carries no date. It is shown at the end, whatever dates you chose.', other: '{count} copies carry no date. They are shown at the end, whatever dates you chose.' },
    'grid.showUndated': 'Show them',
    'grid.hidden': 'Not shown: {list}.',
    'grid.hidden.smaller': { one: '1 smaller copy', other: '{count} smaller copies' },
    'grid.hidden.dates': { one: '1 from outside the dates chosen', other: '{count} from outside the dates chosen' },
    'grid.hidden.elsewhere': { one: '1 from another folder', other: '{count} from other folders' },
    'grid.hidden.tiny': { one: '1 tiny picture', other: '{count} tiny pictures' },
    'grid.showSmaller': { one: 'Show the smaller copy', other: 'Show the {count} smaller copies' },
    'grid.showTiny': { one: 'Show the tiny picture', other: 'Show the {count} tiny pictures' },
    'grid.filter.size': 'Show',
    'grid.filter.full': 'Full size only',
    'grid.filter.smaller': 'Include smaller copies',
    'grid.filter.minSize': 'Hide tiny pictures (under {px} pixels)',
    'grid.filter.from': 'Found in',
    'grid.filter.allSources': 'Every place',
    'grid.jump': 'Jump to',
    'grid.jumpPick': 'Choose a month',
    'grid.month': '{month} ({count})',
    'grid.noDate': 'No date',
    'grid.noDate.body': 'These copies carry no date, such as a thumbnail whose file is unknown. They are always shown, whatever dates you chose.',
    'grid.keys': 'In the grid, arrow keys move, Space selects, Shift+Space selects a range, and Enter opens.',
    'grid.selected': { one: '{count} selected ({size})', other: '{count} selected ({size})' },
    'grid.restoreSelected': 'Restore selected…',
    'grid.select': 'Select',
    'grid.tileLabel': '{type}, {when}, {tier}, {size}',
    'grid.tileLabelNamed': '{type} {name}, {when}, {tier}, {size}',
    'grid.type.photo': 'Photo',
    'grid.type.video': 'Video',
    'grid.noThumb': 'No preview',
    'grid.loadingThumb': 'Loading…',

    // ---- what a copy is ----
    'tier.exact': 'Exact copy',
    'tier.exact.help': 'The file’s own bytes, exactly as they were saved.',
    'tier.inexact': 'Inexact copy',
    'tier.inexact.help': 'Saved, but not provably the bytes that were on disk. For text, line breaks, an invisible mark at the start or the last line break may differ. For a file read back from a card or USB stick, another file may have been written where it lay since.',
    'tier.inexact.help.text': 'Saved, but not provably the bytes that were on disk: line breaks, an invisible mark at the start or the last line break may differ. Fine to read; check it where every byte counts.',
    'tier.inexact.help.disk': 'The drive recorded where this file lay, and its content checks out as far as its format allows, but nothing proves another file was not written there since. Look at it before relying on it.',
    'tier.draft': 'Never saved',
    'tier.draft.help': 'Text typed into an editor and never saved to the file. It may be newer than any saved copy, or unfinished.',
    'tier.unverified': 'May be incomplete',
    'tier.unverified.help': 'Read back from space the drive had marked free, or taken as lying in one piece. It passed the checks its format allows, but parts of it may be missing or belong to another file.',
    'tier.derived': 'Smaller copy',
    'tier.derived.size': 'Smaller copy, {w} × {h}',
    'tier.derived.help': 'A reduced or re-encoded picture that Windows or an app made to show the file, such as a thumbnail. It is not the original photo or video.',
    'tier.folder': 'Folder',
    'tier.folder.help': 'A whole deleted folder, with what was inside it.',
    'tier.gone': 'Empty',
    'tier.gone.help': 'A place still lists this item, but its contents are gone.',

    'state.deleted': 'Deleted',
    'state.deleted.help': 'Nothing is at the original place any more.',
    'state.exists': 'Still there',
    'state.exists.help': 'Something is at the original place now; this copy is an older version of it.',
    'state.noContent': 'No content',
    'state.noContent.help': 'Listed, but its contents are gone.',
    'state.unknown': 'Can’t check',
    'state.unknown.help': 'The original place is on another computer, a network drive or a disk that is not connected, or its folder is unknown, so whether the file is still there cannot be told.',

    // What a copy's date means, which depends on where it was found.
    'time.deleted': 'Deleted on {date}',
    'time.modified': 'Changed on {date}',
    'time.saved': 'Saved on {date}',
    'time.written': 'Written on {date}',
    'time.read': 'Read on {date}',
    'time.backedUp': 'Copied on {date}',
    'time.committed': 'Committed on {date}',
    'time.unknown': '{date}',
    'time.none': 'Date unknown',

    // ---- where a copy was found: 'kind.' + the library's kind ----
    'kind.recycle bin': 'Recycle Bin',
    'kind.recycle bin, inside a deleted folder': 'Recycle Bin, in a deleted folder',
    'kind.local history': 'Editor history',
    'kind.unsaved editor buffer': 'Editor, unsaved changes',
    'kind.claude backup': 'Claude Code backup',
    'kind.claude backup, name unknown': 'Claude Code backup, name unknown',
    'kind.claude write': 'Written by Claude Code',
    'kind.claude read': 'Read by Claude Code',
    'kind.claude, before a write': 'Before Claude Code rewrote it',
    'kind.claude, before an edit': 'Before a Claude Code edit',
    'kind.claude, after an edit': 'After a Claude Code edit',
    'kind.antigravity write': 'Written by Antigravity',
    'kind.antigravity write, final newline unknown': 'Written by Antigravity, last line break unknown',
    'kind.antigravity read': 'Read by Antigravity',
    'kind.git commit': 'git history',
    'kind.git index': 'git staging area',
    'kind.git, deleted in a commit': 'git, the version before a commit deleted it',
    'kind.git, Git LFS pointer': 'git, Git LFS pointer',
    'kind.git lfs object, name unknown': 'git LFS storage, name unknown',
    'kind.git object, name unknown, as stored': 'git storage, name unknown',
    'kind.git, filter not run': 'git, filter not applied',
    'kind.git, line endings differ': 'git, line breaks may differ',
    'kind.shadow copy': 'Restore point',
    'kind.jetbrains history': 'JetBrains or Android Studio history',
    'kind.jetbrains history, as text': 'JetBrains or Android Studio history, as text',
    'kind.jetbrains cache': 'JetBrains or Android Studio cache',
    'kind.jetbrains cache, name unknown': 'JetBrains or Android Studio cache, name unknown',
    'kind.eclipse history': 'Eclipse history',
    'kind.eclipse history, name unknown': 'Eclipse history, name unknown',
    'kind.notepad, as last saved': 'Notepad, as last saved',
    'kind.notepad, edits never saved': 'Notepad, unsaved changes',
    'kind.notepad, untitled, never saved': 'Notepad, untitled tab',
    'kind.hancom autosave': 'Hangul autosave',
    'kind.hancom backup': 'Hangul backup (.bak)',
    'kind.trash': 'Linux trash',
    'kind.trash, inside a deleted folder': 'Linux trash, in a deleted folder',
    'kind.trash, name unknown': 'Linux trash, name unknown',
    'kind.thumbnail': 'Windows thumbnail',
    'kind.thumbnail, name unknown': 'Windows thumbnail, name unknown',
    'kind.fat undelete': 'Undeleted from a FAT drive',
    'kind.exfat undelete': 'Undeleted from an exFAT drive',
    'kind.carved': 'Found in free space',
    'kind.snipping tool capture': 'Snipping Tool capture',

    'kind.unknownHelp': 'Found by the “{source}” search.',
    'kindHelp.recycle bin': 'Windows moved it to the Recycle Bin when it was deleted. This is the file itself.',
    'kindHelp.recycle bin, inside a deleted folder': 'The folder it was in was moved to the Recycle Bin, with this file inside.',
    'kindHelp.local history': 'Your code editor (VS Code, Cursor, Antigravity and others) kept a copy each time the file was saved.',
    'kindHelp.unsaved editor buffer': 'Your code editor kept changes you had not saved yet, so that closing it would not lose them.',
    'kindHelp.claude backup': 'Claude Code copied the file before changing it.',
    'kindHelp.claude backup, name unknown': 'Claude Code copied a file before changing it, but its name was not recorded.',
    'kindHelp.claude write': 'The full text Claude Code wrote into the file.',
    'kindHelp.claude read': 'Text Claude Code read from the file. Line breaks may differ from the file.',
    'kindHelp.claude, before a write': 'What the file held just before Claude Code wrote over it.',
    'kindHelp.claude, before an edit': 'What the file held just before a Claude Code edit.',
    'kindHelp.claude, after an edit': 'Put together by applying an edit Claude Code recorded to an earlier copy.',
    'kindHelp.antigravity write': 'The full text Antigravity’s agent wrote into the file.',
    'kindHelp.antigravity write, final newline unknown': 'The text Antigravity’s agent wrote; whether the file ended with a line break is not known.',
    'kindHelp.antigravity read': 'Text Antigravity’s agent read from the file.',
    'kindHelp.git commit': 'A version kept in a git repository’s history.',
    'kindHelp.git index': 'The version last staged with git add, never committed.',
    'kindHelp.git, deleted in a commit': 'The version the file had just before a commit deleted it.',
    'kindHelp.git, Git LFS pointer': 'The small pointer file git keeps for a large file stored elsewhere.',
    'kindHelp.git lfs object, name unknown': 'A large file git stored, whose name was not recorded.',
    'kindHelp.git object, name unknown, as stored': 'Content found in git’s storage, not tied to any name.',
    'kindHelp.git, filter not run': 'git keeps this file through a filter that was not run, so the bytes may differ from what was on disk.',
    'kindHelp.git, line endings differ': 'git changes line breaks when it writes this file out; they may differ from the original.',
    'kindHelp.shadow copy': 'Windows kept a snapshot of the drive (a restore point). This is the file as it was then.',
    'kindHelp.jetbrains history': 'JetBrains IDEs and Android Studio keep each file as it was before a change, for about five days.',
    'kindHelp.jetbrains history, as text': 'Kept by the IDE as editor text; line breaks and the mark at the start may differ.',
    'kindHelp.jetbrains cache': 'The last content the IDE saw of the file.',
    'kindHelp.jetbrains cache, name unknown': 'Content the IDE saw, whose name was not recorded.',
    'kindHelp.eclipse history': 'Eclipse kept each version the file had before it was replaced.',
    'kindHelp.eclipse history, name unknown': 'A version Eclipse kept, whose name was not recorded.',
    'kindHelp.notepad, as last saved': 'Notepad kept the text of the file as it was last saved, and it matches the fingerprint Notepad recorded.',
    'kindHelp.notepad, edits never saved': 'Changes typed into Notepad and never saved to the file.',
    'kindHelp.notepad, untitled, never saved': 'Text typed into a Notepad tab that was never saved anywhere.',
    'kindHelp.hancom autosave': 'Hangul’s automatic save, left behind when it did not close normally.',
    'kindHelp.hancom backup': 'Hangul’s backup of the version before the last save.',
    'kindHelp.trash': 'A Linux desktop moved it to its trash when it was deleted.',
    'kindHelp.trash, inside a deleted folder': 'The folder it was in was moved to a Linux trash.',
    'kindHelp.trash, name unknown': 'An item in a Linux trash whose original name was not recorded.',
    'kindHelp.thumbnail': 'A smaller picture Windows Explorer made to show the file, tied to it by a record Windows kept. It is not the file itself, and may show an earlier or later version of it.',
    'kindHelp.thumbnail, name unknown': 'A smaller picture Windows Explorer made to show a file. Which file, and when, Windows did not record.',
    'kindHelp.fat undelete': 'Read back from a memory card, USB stick or disk image (FAT) where the file was marked deleted, with the name and size the drive recorded. The space was free after that, so a later file may have been written over part of it.',
    'kindHelp.exfat undelete': 'Read back from a memory card, USB stick or disk image (exFAT) where the file was marked deleted, with the name and size the drive recorded. The space was free after that, so a later file may have been written over part of it.',
    'kindHelp.carved': 'Found by its content in the free space of a drive or disk image, with no name. It may be incomplete, or a picture that was inside another file.',
    'kindHelp.snipping tool capture': 'A screenshot or screen recording the Snipping Tool kept in its own folder.',

    // ---- what is searched ----
    'sources.title': 'What is searched on this PC',
    'sources.intro': 'Solarljos looks in each of these places. None of them is changed.',
    'sources.elevated': 'Solarljos is running as administrator, so it can read memory cards and USB sticks directly.',
    'sources.onlyAdded': 'Search only the places I added, and leave out this PC’s own',
    'sources.checking': 'Checking…',
    'sources.needsAdmin': 'Needs administrator rights to read a drive itself. Run Solarljos as administrator, or add an image of the drive.',
    'sources.textOnly': 'Keeps only text, so a search for photos and videos leaves it out.',
    'sources.frozen': 'Read when Solarljos started ({when}), before this window opened: what Windows adds from now on changes nothing here.',
    'sources.frozenFailed': 'Could not be read ahead when Solarljos started: {error}',
    'sources.keeps': 'What it keeps',
    'sources.howLong': 'For how long',
    'sources.technical': 'What it sees here',
    'sources.noLines': 'Nothing to report.',
    'sources.describeFailed': 'What it sees could not be asked for: {message}',
    'sources.add': 'Add a place from another disk…',
    'sources.added': 'Added for this session',
    'sources.addedNow': '{source}: place added for this session.',
    'sources.removedNow': '{source}: place removed.',
    'sources.remove': 'Remove',
    'sources.addTitle': 'Add a place for {source}',
    'sources.addPlace.label': 'Folder on the other disk',
    'sources.addHint': 'The folder on the other disk. Solarljos only reads it, and forgets it when this window is closed.',
    'sources.addLabel.vss': 'Folder to look through',
    'sources.addHint.vss': 'A folder to look through in every restore point, such as C:\\Users\\you\\Pictures. It can be one that no longer exists.',
    'sources.addLabel.removable': 'Disk image or drive',
    'sources.addHint.removable': 'An image of a memory card or USB stick, made with another tool, or the card’s drive letter, such as E:. Reading the card itself needs administrator rights.',
    'sources.addHint.git': 'A folder to look for git repositories in: it, two levels below it, and the repository it is in.',
    'sources.addSubmit': 'Add',
    'sources.walkPlace': '{folder}, in every restore point',

    'source.recycle.label': 'Recycle Bin',
    'source.recycle.keeps': 'Files and folders you deleted, with where they were and when.',
    'source.recycle.howLong': 'Until the Recycle Bin is emptied, or fills up and drops the oldest.',
    'source.history.label': 'Editor history',
    'source.history.keeps': 'A copy of a file each time you saved it in VS Code, Cursor, Antigravity or a similar editor.',
    'source.history.howLong': 'Many saves back, until the editor trims it.',
    'source.claude.label': 'Claude Code',
    'source.claude.keeps': 'Backups Claude Code took before changing files, and what it read and wrote.',
    'source.claude.howLong': 'About a month by default.',
    'source.antigravity.label': 'Antigravity',
    'source.antigravity.keeps': 'What Antigravity’s agent read and wrote.',
    'source.antigravity.howLong': 'As long as the conversations are kept.',
    'source.git.label': 'git',
    'source.git.keeps': 'Every committed version, staged files, and commits thrown away by a reset.',
    'source.git.howLong': 'Committed versions stay; thrown-away commits for weeks to months.',
    'source.jetbrains.label': 'JetBrains IDEs',
    'source.jetbrains.keeps': 'Each file as it was before a change in a JetBrains IDE or Android Studio.',
    'source.jetbrains.howLong': 'About five days.',
    'source.eclipse-history.label': 'Eclipse history',
    'source.eclipse-history.keeps': 'Each version a file had before Eclipse replaced it.',
    'source.eclipse-history.howLong': 'A week by default.',
    'source.notepad.label': 'Windows Notepad',
    'source.notepad.keeps': 'Text typed into Notepad tabs and never saved.',
    'source.notepad.howLong': 'While the tab stays open.',
    'source.editor-backups.label': 'Unsaved editor changes',
    'source.editor-backups.keeps': 'Changes not saved yet in VS Code and similar editors.',
    'source.editor-backups.howLong': 'Until they are saved or thrown away.',
    'source.hancom.label': 'Hancom Office',
    'source.hancom.keeps': 'Hangul’s autosaves and .bak backups.',
    'source.hancom.howLong': 'Autosaves until Hangul closes normally; backups until the next save.',
    'source.trash.label': 'Linux trash',
    'source.trash.keeps': 'Files deleted on Linux, including on drives used there.',
    'source.trash.howLong': 'Until the trash is emptied.',
    'source.thumbcache.label': 'Explorer thumbnails',
    'source.thumbcache.keeps': 'Smaller pictures Windows Explorer made of the photos, videos and documents it showed.',
    'source.thumbcache.howLong': 'Until Windows clears the thumbnail cache, as Disk Cleanup does.',
    'source.snips.label': 'Snipping Tool',
    'source.snips.keeps': 'Screenshots and screen recordings the Snipping Tool took, kept in its own folder even when they were never saved.',
    'source.snips.howLong': 'Until the Snipping Tool clears its folder, or is reinstalled.',
    'source.removable.label': 'Memory cards and USB sticks',
    'source.removable.keeps': 'Files deleted from a memory card, a USB stick or an image of one (FAT or exFAT), which Windows does not erase at once.',
    'source.removable.howLong': 'Until something new is written over them.',
    'source.vss.label': 'Restore points',
    'source.vss.keeps': 'Snapshots of whole drives that Windows takes for restore points.',
    'source.vss.howLong': 'Until Windows removes old ones to make room; often only a few exist.',

    // ---- preview ----
    'preview.title': 'Preview',
    'preview.loading': 'Loading…',
    'preview.tab.picture': 'Picture',
    'preview.tab.video': 'Video',
    'preview.tab.text': 'Text',
    'preview.tab.hex': 'Bytes',
    'preview.tab.info': 'About this copy',
    'preview.folder': 'A whole folder. What it holds is not shown here; restore it to see.',
    'preview.empty': 'This copy is empty: it holds no bytes.',
    'preview.allZero': 'This copy is all zero bytes. Its data is gone: the drive erased it after the file was deleted, and it cannot be recovered from here.',
    'preview.startsZero': 'The first {size} of this copy are all zero bytes. Its data has probably been erased, as an SSD does soon after a file is deleted.',
    'preview.extMismatch': 'The name ends in {ext}, but the bytes are {format}.',
    'preview.unknownContent': 'The name ends in {ext}, but the bytes are not in any format Solarljos knows: the copy may be damaged, or hold something else.',
    'preview.none.gone': 'Nothing of this copy is left to show.',
    'preview.none.format': 'This file ({format}) can’t be shown here. Restore it to open it with its app.',
    'preview.imageAlt': 'Picture: {name}',
    'preview.image.cannot': 'This browser can’t show {format} pictures. Restore it and open it with the Photos app.',
    'preview.video.cannot': 'This browser can’t play this video ({format}). Restore it and open it with a video player.',
    'preview.encoding': 'Read as {encoding}',
    'preview.encoding.label': 'Read as',
    'preview.encoding.auto': 'Automatic',
    'preview.encoding.utf8': 'UTF-8',
    'preview.encoding.utf16le': 'UTF-16, little-endian',
    'preview.encoding.utf16be': 'UTF-16, big-endian',
    'preview.encoding.korean': 'Korean (EUC-KR, CP949)',
    'preview.encoding.western': 'Western (Windows-1252)',
    'preview.textTruncated': 'Showing the first {shown} of {size}.',
    'preview.svgAsText': 'Drawings (SVG) are shown as text, so nothing in them can run.',
    'preview.wrap': 'Wrap long lines',
    'preview.hexSummary': 'Starts with {magic}: this is {format}.',
    'preview.hexUnknown': 'Starts with {magic}: what format this is could not be told from its first bytes.',
    'preview.hexPage': 'Bytes {from} to {to} of {size}',
    'preview.hexPrev': 'Previous',
    'preview.hexNext': 'Next',
    'preview.hex.caption': 'The bytes of this copy, sixteen to a row',
    'preview.hex.offset': 'Offset',
    'preview.hex.bytes': 'Bytes',
    'preview.hex.text': 'As text',
    'preview.info.path': 'Was at',
    'preview.info.when': 'Date',
    'preview.info.size': 'Size',
    'preview.info.dimensions': 'Size in pixels',
    'preview.info.format': 'Format',
    'preview.info.formatIs': '{format}, as its first bytes say',
    'preview.info.quality': 'Copy',
    'preview.info.state': 'Now',
    'preview.info.foundIn': 'Found in',
    'preview.info.alsoIn': 'The same content was also found in',
    'preview.info.keptAt': 'This copy is kept at',
    'preview.info.note': 'Note',
    'preview.info.id': 'ID',
    'preview.info.idHint': 'The same ID the command line shows.',
    'preview.technical': 'Technical details',
    'preview.prevItem': 'Previous',
    'preview.nextItem': 'Next',

    // ---- restoring ----
    'restore.title.one': 'Put back {name}',
    'restore.title.many': { one: 'Put back 1 item', other: 'Put back {count} items' },
    'restore.dest.label': 'Save to',
    'restore.dest.hint': 'A folder is made if it doesn’t exist. Nothing already there is replaced: a name that is taken gets “(recovered 2)”.',
    'restore.drives': 'Drives',
    'restore.drive.system': 'Windows',
    'restore.drive.original': 'where the files were',
    'restore.driveFree': '{free} free',
    'restore.folderName': 'Solarljos recovered',
    'restore.suggest.exeDrive': 'Suggested: the drive Solarljos runs from ({drive}), which is not where the file was.',
    'restore.suggest.otherDrive': 'Suggested: drive {drive}, which is not where the file was.',
    'restore.suggest.desktop': 'Suggested: a new folder on your Desktop. There is no other drive to use.',
    'restore.suggest.home': 'Suggested: a new folder in your user folder. There is no other drive to use.',
    'restore.useSuggested': 'Use {path} instead',
    'restore.name': 'Will be saved as {name}, or with “(recovered 2)” added if that name is taken.',
    'restore.nameSmaller': 'This is a smaller copy, not the original. It is saved with “(smaller copy {size})” in its name.',
    'restore.nameSmallerNoSize': 'This is a smaller copy, not the original. It is saved with “(smaller copy)” in its name.',
    'restore.nameDraft': 'This text was never saved to the file. It may be unfinished.',
    'restore.nameNear': 'This copy is inexact: small details such as line breaks may differ from the file.',
    'restore.nameNearDisk': 'This copy is inexact: the card recorded where the file lay, but a later file may have been written there since. Look at it before relying on it.',
    'restore.nameIncomplete': 'This copy may be incomplete. It is saved with “(may be incomplete)” in its name.',
    'restore.folder': 'This is a whole folder. It is saved as a new folder named {name}.',
    'restore.many.derived': { one: '1 is a smaller copy; its name will say so.', other: '{count} are smaller copies; their names will say so.' },
    'restore.many.unverified': { one: '1 may be incomplete; its name will say so.', other: '{count} may be incomplete; their names will say so.' },
    'restore.many.draft': { one: '1 is text that was never saved.', other: '{count} are text that was never saved.' },
    'restore.many.leftOut': { one: '1 file is a smaller copy or may be incomplete; its name will say so.', other: '{count} files are smaller copies or may be incomplete; their names will say so.' },
    'restore.submit': 'Restore',
    'restore.submitMany': { one: 'Restore 1 item', other: 'Restore {count} items' },
    'restore.working': 'Restoring…',
    'restore.progress': 'Restored {done} of {total}…',
    'restore.done.one': 'Restored to',
    'restore.done.many': { one: '1 item restored into', other: '{count} items restored into' },
    'restore.done.none': 'Nothing was restored',
    'restore.done.failed': { one: '1 could not be restored:', other: '{count} could not be restored:' },
    'restore.openWarning': 'When you open this folder in File Explorer, Windows makes thumbnails of what is in it, and may drop old ones to make room. This session read them when it started, so nothing here changes; if you mean to look for photos again another day, do it before opening the folder.',

    'dest.checking': 'Checking the folder…',
    'dest.missing': 'Give a folder.',
    'dest.relative': 'Give the whole folder, starting with the drive letter, such as D:\\Recovered.',
    'dest.newFolder': 'The folder will be made.',
    'dest.sameDrive.title': 'This is the drive the file was on ({drive})',
    'dest.sameDrive.body': 'If it is a hard disk, a memory card or a USB stick, writing here can overwrite other deleted files that could still be found. On any drive, writing a lot can make Windows remove old restore points. Choose another drive if you can.',
    'dest.sameDrive.many': { one: '1 of the items was on this drive.', other: '{count} of the items were on this drive.' },
    'dest.sameDrive.confirm': 'I understand; save here anyway',
    'dest.sameDrive.unknown': 'Drives cannot be told apart by their paths here. If the files were lost from the disk this folder is on, choose a folder on another disk.',
    'dest.onDevice.title': 'This may be the card or stick being recovered',
    'dest.onDevice.body': { one: '1 of the items was read from a whole disk, whose drive letter cannot be told here. If this folder is on that card or stick, saving here can overwrite other deleted files; choose a folder on the Windows drive or another disk.', other: '{count} of the items were read from a whole disk, whose drive letter cannot be told here. If this folder is on that card or stick, saving here can overwrite other deleted files; choose a folder on the Windows drive or another disk.' },
    'dest.systemDrive': 'This is the Windows drive. Restoring a lot here can push out old restore points.',
    'dest.refused.title': 'Can’t save here',
    'dest.cloud': 'This looks like a folder {service} syncs: what you restore here may be uploaded.',
    'dest.network': 'This is a network folder. It works, but a drive of this PC or a USB stick is safer.',
    'dest.space': 'Needs {needed}; {free} free.',
    'dest.spaceAtLeast': 'Needs at least {needed}; {free} free.',
    'dest.noSpace': 'Not enough space: needs {needed}, only {free} free.',

    // ---- nothing found ----
    'empty.name.title': 'No copies of “{name}” were found',
    'empty.containing.title': 'No copy containing “{text}” was found',
    'empty.type.title': 'No files of the kind {type} were found',
    'empty.media.title': 'No photos or videos were found',
    'empty.folder.title': 'Nothing was found that was inside {folder}',
    'empty.why': 'Why this can happen',
    'empty.why.nowhere': { one: 'The 1 place searched kept no copy. Solarljos finds only copies; on an SSD the deleted file itself is erased soon after.', other: 'None of the {count} places searched kept a copy. Solarljos finds only copies; on an SSD the deleted file itself is erased soon after.' },
    'empty.why.failed': { one: '1 place could not be searched: {names}.', other: '{count} places could not be searched: {names}.' },
    'empty.why.filters': 'The search was limited: {filters}.',
    'empty.why.old': 'Most of these places keep copies for days or weeks; a file lost months ago is often past them.',
    'empty.why.neverOpened': 'A file that was never opened in an editor, never in git and never in a restore point leaves no copy behind.',
    'empty.why.ssd': 'On an SSD a deleted photo or video is erased soon after; what survives are other copies, and none were found.',
    'empty.why.video': 'Old videos rarely survive anywhere but the Recycle Bin, restore points, the card or phone they came from, or a cloud backup.',
    'empty.filter.deletedOnly': 'only files that are gone now',
    'empty.filter.dates': 'only some dates',
    'empty.filter.sources': { one: 'only 1 place', other: 'only {count} places' },
    'empty.filter.type': 'only one kind of file',
    'empty.filter.onlyAdded': 'only the places you added',
    'empty.try': 'What you can try',
    'empty.try.shorter': 'Search for “{part}”',
    'empty.try.containing': 'Search for a word it contained',
    'empty.try.noFilters': 'Search again without the limits',
    'empty.try.where': 'Bring back its folder instead',
    'empty.try.otherDisk': 'Add another disk',
    'empty.try.spelling': 'Check the folder, drive letter included. A file you remember from inside it can also be found by its name.',
    'empty.try.card': 'If the photos were on a memory card or USB stick, read the card itself: run Solarljos as administrator, or add an image of the card under “What is searched”.',
    'empty.elsewhere': 'Where else a copy may be',
    'empty.else.cloud': 'Your cloud storage’s own recycle bin: OneDrive and iCloud keep deleted files for about 30 days, Google Photos for about 60.',
    'empty.else.phone': 'Your phone’s gallery: “Recently deleted” keeps photos for about 30 days.',
    'empty.else.chat': 'Chat rooms where you sent or received the photo.',
    'empty.else.email': 'Emails you sent it in, as an attachment.',
    'empty.else.copies': 'USB sticks, memory cards or other computers you copied it to.',
    'empty.else.app': 'The app’s own version history, such as File › Info › Version History in Office.',
    'empty.details': 'What each place reported',
    'empty.noLongerThere': 'This copy is no longer where it was; the Recycle Bin may have been emptied since the search. Search again.',

    // ---- errors ----
    'error.title': 'Something went wrong',
    'error.usage': 'Solarljos could not use that.',
    'error.forbidden': 'This page is not connected to this run of Solarljos. Use the window Solarljos opened, or start it again.',
    'error.notFound': 'These results are no longer kept. Search again.',
    'error.busy': 'Another search is still running.',
    'error.gone': 'Nothing of this copy is left to read.',
    'error.tooLarge': 'That request is too large.',
    'error.format': 'This kind of file can’t be shown here.',
    'error.offline': 'Solarljos did not answer.',
    'error.io': 'Could not read or write: {message}',
    'error.io.ENOSPC': 'The drive is full.',
    'error.io.EACCES': 'Windows did not allow access to this folder.',
    'error.io.EPERM': 'Windows did not allow this. The folder may be protected, or a file is open in another program.',
    'error.io.ENAMETOOLONG': 'The name or folder path is too long for Windows.',
    'error.io.ENOENT': 'The folder or drive is not there any more.',
    'error.io.EIO': 'The drive reported a read or write error.',
    'error.io.EROFS': 'This drive can only be read.',
    'error.io.EBUSY': 'The file is in use by another program.',
    'error.io.EEXIST': 'A file of that name appeared while writing; nothing was replaced.',
    'error.unexpected': 'Something unexpected went wrong.',

    // ---- help ----
    'help.title': 'Help',
    'help.what.title': 'What Solarljos does',
    'help.what.body': 'When a file is deleted from a PC with an SSD, the drive erases it soon after. What survives are other copies: in the Recycle Bin, in restore points, in the history an editor or IDE keeps, in AI coding agents’ records, in git, in tabs Notepad never saved, in smaller pictures Windows made. Solarljos looks in all of them at once.',
    'help.tiers.title': 'Reading the labels',
    'help.states.title': 'Is the file still there?',
    'help.media.title': 'Photos and videos',
    'help.media.ssd': 'A photo deleted from an SSD long ago usually survives only as a smaller copy, in a restore point, in a chat app or in a cloud backup. A smaller copy is never passed off as the original: it is labelled, and its name says so when it is restored.',
    'help.media.video': 'Old videos rarely survive on an SSD. Windows keeps at most a still picture of a video. Look in the Recycle Bin and restore points, on the card or phone the video came from, and in cloud backups.',
    'help.media.card': 'Memory cards and USB sticks keep deleted files longer. Reading one directly needs administrator rights, or an image of the card made with another tool. Set the card’s lock switch before you put it in, and copy nothing onto it.',
    'help.cant.title': 'What it can’t do',
    'help.cant.formatted': 'Bring back files from a formatted or broken disk. That needs a disk recovery service.',
    'help.cant.nocopy': 'Find a file that no app ever kept a copy of.',
    'help.cant.original': 'Turn a smaller copy of a photo back into the full-size original.',
    'help.writes.title': 'What is written',
    'help.writes.body': 'Nothing, except the files you choose to restore, in the folder you choose. Solarljos keeps no settings, history or log, and your results live only in its memory until you quit. What Windows does whenever any program runs, such as noting that it started, no program can prevent.',
    'help.stop.title': 'When Solarljos stops',
    'help.stop.body': 'Solarljos runs only while this window is open: closing the window, or Quit, stops it a few seconds later, and nothing of it is left running. It never stops in the middle of a restore; a restore under way is finished first.',
    'help.browser.title': 'This window and your browser',
    'help.browser.inprivate': 'Solarljos opened this page in a Microsoft Edge InPrivate window, so Edge keeps no history, cookies or cache of it. If Edge was not already running, it still writes what it writes whenever it starts: its settings and start-up files in your profile.',
    'help.browser.default': 'Solarljos opened this page in your usual browser, which records the visit in its history, the page’s address included. That address works only once, and has been used: nothing can open this page from it again.',
    'help.browser.none': 'You opened this page yourself. What your browser records of the visit depends on the browser and its settings.',
    'help.browser.unknown': 'Your browser may note the visit to this page in its history, and writes its own settings as it always does. Nothing else of this page is kept: it is sent with instructions not to be stored, and it keeps nothing in the browser’s storage.',
    'help.browser.save': 'To keep a copy, use Restore. The page leaves out the browser’s own “Save image as”, “Save video as”, the video player’s Download and Ctrl+S, since a browser download goes into your Downloads folder on the Windows drive, past the checks Restore makes of where it writes.',
    'help.keys.title': 'Keyboard',
    'help.keys.body': 'Tab moves between controls. In the photo grid and the folder list, arrow keys move, Space selects and Enter opens. Esc closes a preview or a dialog.',
    'help.version': 'Version {version}',
    'desktop.help.window.title': 'This window',
    'desktop.help.window.body': 'Solarljos is a program of its own and opens no browser. It has no folder picker and never opens File Explorer: both show small pictures of what a folder holds, which Windows keeps in the very thumbnail cache a search for photos reads. Type or paste a folder instead. To keep a copy, use Restore, which checks where it writes.',
    'desktop.help.keys.rail': 'In the menu, Up and Down go to the part above or below, and Ctrl+1 to Ctrl+5 go to each part from anywhere in the window.',
  };

  const STRINGS = { en };
  if (typeof module === 'object' && module && module.exports) module.exports = STRINGS;
  else root.SolarljosStrings = STRINGS;
})(typeof globalThis !== 'undefined' ? globalThis : this);
